erlem_jobeet_homepage:
    pattern:  /
    defaults: { _controller: ErlemJobeetBundle:Job:index }
 
ErlemJobeetBundle_job:
    resource: "@ErlemJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job